name: Publish

on:
    workflow_dispatch:
#    push:
#        branches:
#            - main

jobs:
    docker-publish:
        name: Publish to Docker Hub
#        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
#              uses: actions/checkout@v3
              uses: actions/checkout@v4
            - name: Bump version
              uses: remorses/bump-version@js
              id: version
              with:
                  version_file: ./VERSION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout code
#              uses: actions/checkout@v3
              uses: actions/checkout@v4
              with:
                  ref: main
            - name: Set up QEMU
#              uses: docker/setup-qemu-action@v1.2.0
              uses: docker/setup-qemu-action@v3.2.0
              with:
                  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            - name: Set up Docker Buildx
#              uses: docker/setup-buildx-action@v1.6.0
              uses: docker/setup-buildx-action@v3.6.1
            - name: Login to DockerHub
#              uses: docker/login-action@v1.14.1
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
#              uses: docker/build-push-action@v2.10.0
              uses: docker/build-push-action@v6.7.0
              with:
                  context: .
                  push: true
                  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
                  tags: |
                      myeager1967/amcrest2mqtt:test
                      myeager1967/amcrest2mqtt:${{ steps.version.outputs.version }}
                  labels: "version=${{ steps.version.outputs.version }}"
